### ISSUE TITLE
pget is missing version information

### ISSUE THREAD

**Issue by philandstuff** [datakami/cognix#2]
If you run `pget version` with the built version you get:

```
pget Version () - Build Time
```

which is missing important build information.

The pget repository has a Makefile that sets appropriate ldflags to include. Can they be included in the nix build too?

**Comment by technillogue** [comment]
0.3.1 has a performance regression for single files

**Comment by philandstuff** [comment]
@technillogue Can you raise as an issue on the pget repo instead?

**Comment by technillogue** [comment]
I mean that the upgrade to 0.3.0 from 0.1.1 in the commit in this repo fixing this issue may be premature
